# Common Model Parameters
hidden_size: 128
batch_size: 256
num_epochs: 10

# GRU Parameters
gru:
  # No additional parameters

# SASRec Parameters
sasrec:
  num_blocks: 2
  num_heads: 1
  dropout_rate: 0.1

# NITNet Parameters
nitnet:
  dilated_channels: 64
  dilations: [1, 2, 1, 2, 1, 2]
  kernel_size: 3

# Caser Parameters
caser:
  num_filters: 16
  filter_sizes: [2, 3, 4]
  dropout_rate: 0.1